### PR TITLE
updating remark-plugins to v1.2.3

### PR DESCRIPTION
**Pull request by annaxuphoto**
This PR accounts for the edge case of malformed redactions, such that there exist characters between bracket sets. I also added CI tests via Github actions to replace Travis CI. Lastly, this PR includes an update for the` remark-plugins` package.

After merging this PR, I will release a patch of this package and create another PR to update the version.

### CODE REVIEW

**Comment by Hamms** [comment]
Would it be possible to get the CI tests running in this repo using GitHub actions first? I'm worried about the possibility of more test failures perpetuating themselves.

**Comment by annaxuphoto** [comment]
Added CI tests, and additionally one block in `parseRestorations` that accounts for malformed redactions, where there exist characters between the pair of brackets.

**Review by Hamms — APPROVED** [review]
Just to confirm: do we have a test covering the malformed brackets edge case that's fixed in this PR? If so, great! If not, let's add one.

Otherwise, this LGTM!

**Comment by annaxuphoto** [comment]
> Just to confirm: do we have a test covering the malformed brackets edge case that's fixed in this PR? If so, great! If not, let's add one.
> 
> Otherwise, this LGTM!

That test lives in `redactable-markdown`, but I'll add one in this package too

**Pull request merged**
